library(maftools)
laml <- read.maf(maf = "13cancers.2oncogene.maf")
getSampleSummary(laml)
getGeneSummary(laml)
# pdf(file = paste("13cancers.2oncogene.maf", "oncoplot.pdf", sep = "."), width = 12, height = 8)
col = RColorBrewer::brewer.pal(n = 4, name = 'Paired')
names(col) = c("deletion of <=200bp","insertion of <=200bp", "multiple base substitution (>=2bp and <=200bp)", "single base substitution")

# #Color coding for FAB classification; try getAnnotations(x = laml) to see available annotations.
# fabcolors = RColorBrewer::brewer.pal(n = 8,name = 'Spectral')
# names(fabcolors) = c("M0", "M1", "M2", "M3", "M4", "M5", "M6", "M7")
# fabcolors = list(FAB_classification = fabcolors)
# oncoplot(maf = laml, colors = col, clinicalFeatures = 'FAB_classification', sortByAnnotation = TRUE, annotationColor = fabcolors)

png(filename = paste("13cancers.2oncogene.maf", "oncoplot.png", sep = "."), width = 1200, height = 600)
oncoplot(maf = laml, top = 11, fontSize = 12, colors = col)
dev.off()
pdf(file = paste("13cancers.2oncogene.maf", "oncoplot.pdf", sep = "."), width = 12, height = 6)
oncoplot(maf = laml, top = 11, fontSize = 12, colors = col)
dev.off()
pdf(file = paste("13cancers.PAX5", "oncoplot.pdf", sep = "."), width = 12, height = 4)
oncoplot(maf = laml, fontSize = 12, colors = col, genes = c("PAX5", "ZCCHC7", "EBLN3P"))
dev.off()
pdf(file = paste("13cancers.TERT", "oncoplot.pdf", sep = "."), width = 12, height = 6)
oncoplot(maf = laml, fontSize = 12, colors = col, genes = c("TERT", "CLPTM1L", "CTD-3080P12.3", "LINC01511", "SLC12A7", "SLC6A18", "SLC6A19", "SLC6A3"))
dev.off()
